### ISSUE TITLE
Unable to run on Windows 10 IoT .NET Core RC2 - RPi

### ISSUE THREAD

**Issue by HakanL** [hhblaze/DBreeze#10]
I used to run DBreeze fine on my RPi, but after the RC2 update it doesn't work any more, getting an error on line 27 in Engine\Scheme.cs. This is the exception:

Additional information: Could not load file or assembly 'System.Threading, Version=4.0.10.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

I tried this in a blank new UWP project. It works if I run it in the x86 emulator, but not when I'm deploying it to RPI2/3 (ARM).

**Comment by hhblaze** [comment]
I think we have to wait for the answer here http://stackoverflow.com/questions/37495572/cant-find-system-threading-4-0-10-on-raspberry-pi-on-windows-10-iot

**Comment by HakanL** [comment]
Yea I posted that to SO after I got this error on a blank project too, so it's not related to DBreeze. So I'm closing this issue since it's not related.

**Comment by HakanL** [comment]
My %userprofile%\.nuget folder was probably corrupt, after several reinstalls, etc I deleted the folder and after that everything is working. So not related to DBreeze at all.

**Comment by hhblaze** [comment]
Very well!
