### ISSUE TITLE
DBreeze 1.75 doesn't work in UWP

### ISSUE THREAD

**Issue by HakanL** [hhblaze/DBreeze#11]
I have Visual Studio 2015 U3. If I create a blank Universal Windows Application and add DBreeze (v 1.75) then I'm getting errors restoring the packages:

Restoring packages for 'App6'.
Restoring packages for c:\users\user\documents\visual studio 2015\Projects\App6\App6\project.json...
Package DBreeze 1.75.0 is not compatible with uap10.0 (UAP,Version=v10.0). Package DBreeze 1.75.0 supports:
  - monoandroid (MonoAndroid,Version=v0.0)
  - net35 (.NETFramework,Version=v3.5)
  - net40 (.NETFramework,Version=v4.0)
  - net45 (.NETFramework,Version=v4.5)
  - netcoreapp1.0 (.NETCoreApp,Version=v1.0)
One or more packages are incompatible with UAP,Version=v10.0.
Package DBreeze 1.75.0 is not compatible with uap10.0 (UAP,Version=v10.0) / win10-arm. Package DBreeze 1.75.0 supports:
  - monoandroid (MonoAndroid,Version=v0.0)
  - net35 (.NETFramework,Version=v3.5)
  - net40 (.NETFramework,Version=v4.0)
  - net45 (.NETFramework,Version=v4.5)
  - netcoreapp1.0 (.NETCoreApp,Version=v1.0)
One or more packages are incompatible with UAP,Version=v10.0 (win10-arm).
Package DBreeze 1.75.0 is not compatible with uap10.0 (UAP,Version=v10.0) / win10-arm-aot. Package DBreeze 1.75.0 supports:
  - monoandroid (MonoAndroid,Version=v0.0)
  - net35 (.NETFramework,Version=v3.5)
  - net40 (.NETFramework,Version=v4.0)
  - net45 (.NETFramework,Version=v4.5)
  - netcoreapp1.0 (.NETCoreApp,Version=v1.0)
One or more packages are incompatible with UAP,Version=v10.0 (win10-arm-aot).
Package DBreeze 1.75.0 is not compatible with uap10.0 (UAP,Version=v10.0) / win10-x64. Package DBreeze 1.75.0 supports:
  - monoandroid (MonoAndroid,Version=v0.0)
  - net35 (.NETFramework,Version=v3.5)
  - net40 (.NETFramework,Version=v4.0)
  - net45 (.NETFramework,Version=v4.5)
  - netcoreapp1.0 (.NETCoreApp,Version=v1.0)
One or more packages are incompatible with UAP,Version=v10.0 (win10-x64).
Package DBreeze 1.75.0 is not compatible with uap10.0 (UAP,Version=v10.0) / win10-x64-aot. Package DBreeze 1.75.0 supports:
  - monoandroid (MonoAndroid,Version=v0.0)
  - net35 (.NETFramework,Version=v3.5)
  - net40 (.NETFramework,Version=v4.0)
  - net45 (.NETFramework,Version=v4.5)
  - netcoreapp1.0 (.NETCoreApp,Version=v1.0)
One or more packages are incompatible with UAP,Version=v10.0 (win10-x64-aot).
Package DBreeze 1.75.0 is not compatible with uap10.0 (UAP,Version=v10.0) / win10-x86. Package DBreeze 1.75.0 supports:
  - monoandroid (MonoAndroid,Version=v0.0)
  - net35 (.NETFramework,Version=v3.5)
  - net40 (.NETFramework,Version=v4.0)
  - net45 (.NETFramework,Version=v4.5)
  - netcoreapp1.0 (.NETCoreApp,Version=v1.0)
One or more packages are incompatible with UAP,Version=v10.0 (win10-x86).
Package DBreeze 1.75.0 is not compatible with uap10.0 (UAP,Version=v10.0) / win10-x86-aot. Package DBreeze 1.75.0 supports:
  - monoandroid (MonoAndroid,Version=v0.0)
  - net35 (.NETFramework,Version=v3.5)
  - net40 (.NETFramework,Version=v4.0)
  - net45 (.NETFramework,Version=v4.5)
  - netcoreapp1.0 (.NETCoreApp,Version=v1.0)
One or more packages are incompatible with UAP,Version=v10.0 (win10-x86-aot).
Package restore failed for 'App6'.
Package restore failed. Rolling back package changes for 'App6'.
========== Finished ==========
Time Elapsed: 00:00:00.8687082

**Comment by hhblaze** [comment]
Let's investigate...
[App1.zip](https://github.com/hhblaze/DBreeze/files/349260/App1.zip)

Here I have created UWP APP and compiled it with NuGet DBreeze for ARM, x86 and x64 (bin and i´bj were deleted, cause of 10MB restriction of github upload)

**Comment by hhblaze** [comment]
may be you can test reference just to DBreeze binaries from your UWP project. Grab binaries from here https://github.com/hhblaze/DBreeze/tree/master/Deployment/bin (there UWP project)

**Comment by hhblaze** [comment]
I have VS2015 Professional Update 3, extra was installed 
NET Core 1.0 for Visual Studio (https://go.microsoft.com/fwlink/?LinkId=817245)
recommended here https://www.microsoft.com/net/core#windows

**Comment by hhblaze** [comment]
Previous nuget package contained folder netcore451 and now I have replaced it with netcoreapp1.0 (all was recommended)
Here, grab enhanced package (restored folder netcore451 in there), test it and, please, let me know 
[DBreeze.1.75.1.zip](https://github.com/hhblaze/DBreeze/files/349272/DBreeze.1.75.1.zip)

Thanx!

**Comment by HakanL** [comment]
Referencing the DLL directly worked fine. From what I can tell I think you should target .netstandard (as low version as possible) instead of netcoreapp1.0, to have support in both CoreCLR and full .NET Framework. I know I can reference .netstandard packages in my UWP application.

**Comment by HakanL** [comment]
The App1 above doesn't work for me (it fails on restoring packages, same error as above, but since there are no references to DBreeze in the code it builds, but if you try to use DBreeze then it won't build either).

**Comment by HakanL** [comment]
The 1.75.1 works too, but I think using .netstandard is the more universal solution (but I may be wrong).

**Comment by hhblaze** [comment]
TOP idea, confirm that this nuget package works for you and I will publish it:

[DBreeze.1.75.2.zip](https://github.com/hhblaze/DBreeze/files/351616/DBreeze.1.75.2.zip)

**Comment by hhblaze** [comment]
I think there is a problem with netstandard, because then DBreeze can be referenced by Portable library...that's not correct. So, I think, I will publish version 1.75.1

With trying to reference v1.75.1 from portable library I got correct exception:

Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not install package 'DBreeze 1.75.1'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile111', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.			0

**Comment by HakanL** [comment]
ok, for your reference 1.75.2 worked in UWP.

Which .netstandard did you use in 1.75.2, according to this: http://blog.stephencleary.com/2012/05/framework-profiles-in-net.html the Portable profile 111 supports .NET standard 1.1, so if you pick 1.2 then you should be fine. Probably cleaner long-term to use netstandard.

**Comment by hhblaze** [comment]
DBreeze is not a ".NET Portable" library, so portable profiles don't fit for now.

**Comment by HakanL** [comment]
Right, but the .NET Standard isn't meant to be related to portable (afaik), it's meant to specify what base .NET support a library needs, but not tied to a particular platform (like UWP, .NET Core, etc). So I think using .NET Standard is the best way for libraries like DBreeze, provides the most flexibility.

**Comment by hhblaze** [comment]
I will take a closer look.
