### ISSUE TITLE
Any chance for a client UI

### ISSUE THREAD

**Issue by xumix** [hhblaze/DBreeze#14]
like Mongo viewer or management studio?

**Comment by hhblaze** [comment]
Due to DBreeze specific to store heterogeneous data in keys and in values, we don't see an abillity to create universal viewer. 
Only programmer knows the schema. 
So, IDE + .NET language or, probably, LinqPad can help.

**Comment by hhblaze** [comment]
![linqpad](https://cloud.githubusercontent.com/assets/486781/18909730/054c9af4-8575-11e6-9da7-837c43036b49.JPG)

**Comment by xumix** [comment]
I see, ok, thank you!

**Comment by hhblaze** [comment]
Normally, we should instantiate DBreeze engine once... but in case with LinqPad it must be done in the beginning of main() and disposed in the end...
