### ISSUE TITLE
Terminating errors in product which uses dbreeze

### ISSUE THREAD

**Issue by anon01924** [hhblaze/DBreeze#17]
Hi DBreeze Team,

I am using a vendor product (ShareGate) which uses DBreeze. A few times a week I receive a terminating error: 

`Problem signature:
       Problem Event Name:                        PowerShell
  NameOfExe:                                        powershell.EXE
  FileVersionOfSystemManagementAutomation:             10.0.10586.117
  InnermostExceptionType:                 System.IO.IOException
  OutermostExceptionType:                DBreeze.Exceptions.DBreezeException
  DeepestPowerShellFrame:                 unknown
  DeepestFrame:                                    DBreeze.DBreezeEngine.InitDb
  ThreadName:                                      CrossP..0fac55c14b4)
  OS Version:                                          6.3.9600.2.0.0.272.7
  Locale ID:                                             1033
`

The product includes an accompanying message: "DataPortal.Fetch failed (Operation Timed Out)."

I know this is a long shot, but can you provide any insight into what's happening? I have gone through the vendor a few times for more info on how to correct or avoid this error with no luck.

Thanks!

**Comment by hhblaze** [comment]
Hi, all these mistakes concern vendor product more then DBreeze. 
DBreeze.DBreezeEngine.InitDb means the start: there no access to the filesystem or files are locked.
Other mistakes cascade is not from DBreeze.
The best way is to talk with the vendor.

**Comment by anon01924** [comment]
Thanks.
