### ISSUE TITLE
Getting error on UWP (RPi Win 10 IoT)

### ISSUE THREAD

**Issue by HakanL** [hhblaze/DBreeze#18]
I'm getting this error when starting my app.
Failed during startup: DBreeze.Exceptions.DBreezeException: Creation of the database folder failed! ---> DBreeze.Exceptions.DBreezeException: Database is not operable, please find out the problem and restart the engine! FSR INIT FAILED: C:\Data\Users\DefaultAccount\AppData\Local\Packages\IoStorm_mr3ez18jctte6\LocalCache\Cache\_DBreezeSchema ---> System.IO.IOException: IO_SharingViolation_File, C:\Data\Users\DefaultAccount\AppData\Local\Packages\IoStorm_mr3ez18jctte6\LocalCache\Cache\_DBreezeSchema

Any clue? This has worked before, not sure exactly what have changed, I upgraded to DBreeze 1.84 and I'm on build 15063 of Windows 10 IoT.

**Comment by HakanL** [comment]
It seems to work after a reboot on the RPi, I wonder if it's just some disposing/closing down issue so the file is kept open, would that be a possibility?

**Comment by hhblaze** [comment]
Hi, DBreeze needs exclusive lock for scheme and transaction files, that's why, it looks like, any of file was busy by another process... please, observe it further

**Comment by HakanL** [comment]
Yea must be an issue with the file kept open, not likely related to DBreeze.
