### ISSUE TITLE
Remove binaries (nupkg) files from GIT

### ISSUE THREAD

**Issue by HakanL** [hhblaze/DBreeze#2]
Probably best to not have binaries in GIT. You can use releases in github if you need to preserve these.

Can you also exclude .suo and bin/obj folders, I recommend a good .gitignore to get started.

**Comment by HakanL** [comment]
You should also exclude the suo files since they are just user settings for your Visual Studio.

**Comment by HakanL** [comment]
I see the nupkg file in github, that should probably be removed as well.

**Comment by hhblaze** [comment]
Where should I store this nupkg file? It belongs to the project.

**Comment by HakanL** [comment]
Most projects don't store it anywhere since it's generated from spec files and uploaded to nuget.org. But if you want to store it then I would suggest as a release in github: https://help.github.com/articles/creating-releases/
