### ISSUE TITLE
Feature Request: Password Protection

### ISSUE THREAD

**Issue by theweavrs** [hhblaze/DBreeze#20]
Password Protection is a very necessary feature. It can be used in storing passwords, or sensitive data or anything else that requires data encryption.

**Comment by hhblaze** [comment]
Are you talking about encryption module integrated into DBreeze? 
Logically separated modules like serializers, compressors, encryptors etc.
we try to hold outside of DBreeze. 
You can reprogram custom serializer (in songs example was used NetJson) to store encrypted and compressed data.

**Comment by theweavrs** [comment]
Oh, I see. I think this issue is then useless haha. Thanks anyways :)
