### ISSUE TITLE
System.IO.Compression.ZLibException: 'The underlying compression routine could not be loaded correctly.' in UWP

### ISSUE THREAD

**Issue by theweavrs** [hhblaze/DBreeze#22]
This exception occurs on Windows 10 Mobile:
`DllNotFoundException: Unable to load DLL 'clrcompression.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)`

On this line of code:
```csharp
tran.TextInsert(TextTableName, record.Id.To_8_bytes_array_BigEndian(), record.GetTextSearchKey());
```

Here are some references: 
http://stackoverflow.com/questions/41185291/unzipping-throws-an-the-underlying-compression-routine-could-not-be-loaded-corr

**Comment by hhblaze** [comment]
Thanks, I will take a look.

**Comment by theweavrs** [comment]
@hhblaze Thanks for the quick response, this is pretty urgent as it is holding back the update for my app. I may download the source code and try to fix this myself (and perhaps make a pull request) but it will be better if you fix this officially.

**Comment by hhblaze** [comment]
Unfortunately, I am away now... I can start from Monday

**Comment by hhblaze** [comment]
By the way, if you find a fix...it's gonna be a HUGE help, I will try to make release asap.

**Comment by Behrooz-Amoozad** [comment]
A probable easy fix is to just ship the dll.
Or make a small wrapper dll with only the required functions and call back
into system.security private objects with reflection.
 I too am away but will probably look at it sooner than monday.


Good luck

**Comment by theweavrs** [comment]
After much research on this bug, it seems it is within the core UWP nuget package. Here is a reference to the issue:
https://github.com/dotnet/corefx/issues/9743

So, I did a hotfix by added this to my `project.json`:
`"runtime.win8-arm.runtime.native.System.IO.Compression": "4.0.1",` 
in `dependencies` array and it works flawlessly now.

Closing the issue as it is temporarily fixed.

**Comment by hhblaze** [comment]
Hi, great, can you post complete project.json here

**Comment by theweavrs** [comment]
Sure, I will do it in a few hours.
