### ISSUE TITLE
Safe Backup of the Database files

### ISSUE THREAD

**Issue by leedavi** [hhblaze/DBreeze#23]
How do we get a safe external backup of the DB?

By "safe" I mean, if the DB is in use, then we want to make a snapshot of the data files while there are no updates in progress.  Because the DB is spread across multiple files, we could potentially save the files out of sync.

I see the internal incremental backup options, but I'd like to backup with a standard system, like command prompt backup of DB.

**Comment by hhblaze** [comment]
Hi, incremental backup is the only solution. So every 30 minutes (configurable value) will appear a new file and this file will be filled up with the data. In 30 minutes this file will be released and can be safely copied to outer subsystem (batch), where can be restored (batch). It emulates safe copy of the DB with the 30 minutes delay. Docu from [20120905]. 

We internally never use that. because all our servers reside inside of VMs with own safety mechanisms.

**Comment by leedavi** [comment]
Yes, I'm think more about issues with clients, with lazy fingers and making mistakes.  We sometimes are asked to restore the previous nights backup.  Using SQL this is easy, because we create a backup periodically and the SQL DB dealer with the snapshot and the incremental updates that happen during the process.  So therefore we have no need to stop the DB and make a snapshot.  

I'm obviously not talking about massive DB here, only web based application systems.  But downtime (on read), even for a short time is a problem!!

Is there some way to ensure the DB is not updated during the snapshot time?  Maybe by using the SynchronizeTables method on ALL tables and then perform a snapshot by copying the system level files to a Db backup folder, and when it's finshed copying dispose of the transaction without commit and let the DB continue as normal?

Do you think this will work?

**Comment by leedavi** [comment]
using (var tran = engine.GetTransaction())
{
	tran.SynchronizeTables("ALLTABLES","ALLTABLES","ALLTABLES");
	// copy the file system now	
}

or 

using (var tran = engine.GetTransaction())
{
	tran.SynchronizeTables("ALLTABLES","ALLTABLES","ALLTABLES");
	// copy the file system now	
	
	tran.commit();
}

**Comment by hhblaze** [comment]
Transaction journal is never released and has file system exclusive lock, but  SynchronizeTables("*") may mean that we have empty transaction journal after executing the command.
Second problem is read mode, if table is being read out it will also be open by files system exclusively. 
That can be tried out (make experiments on your own):

using(var t = engine.getTran){

t.SynchronizeTables("*")  - no writes at all e.g.
//at this moment definitely tran journal must be empty and we don't need to back it up
foreach file2beCopied //get at this moment from scheme, we need just table and its .rhp
while(true){
try{ 
move file from backup folder to db-folder / or from db-backup 
//!!note better not to restore on hot db, it can cause reading mistakes
}
catch
{ 
//can fail if other threads area reading from this table, so trying again...
continue;
}
break; //all is good this concrete file was backed up 
}

}

**Comment by hhblaze** [comment]
_DBreezeResources, _DBreezeSchema, _DBreezeTextIndexer ...

DBreezeSchema definitely will not give you abilities to be copied...but this is a small problem.
Other files may be in the same loop with try/catch, from time to time they are released.

**Comment by Nu11u5** [comment]
👍
