### ISSUE TITLE
implement meaningful exception messages

### ISSUE THREAD

**Issue by theweavrs** [hhblaze/DBreeze#25]
Currently, all db related exceptions display almost the same message and tells to restart the engine. It would be good practice to implement full error messages. Moreover, it will help in debugging.

**Comment by hhblaze** [comment]
There is exception class all necessary and possible exceptions are covered. Be more precised.

**Comment by theweavrs** [comment]
Just went to see what you meant. All exceptions are implemented so this issue should be closed. I just keep getting only once exception no matter where the code breaks down:

```
Database is not operable, please find out the problem and restart the engine! {0}",message), innerException);
```

And I went to see the code and it seems, this is the general Exception.

**Comment by hhblaze** [comment]
Database is not operable - this is exceptional case. It can happen if HDD fails or the thread, that executes transaction, is aborted on the commit phase (that is wrong program behavior). So, I would say if u see that - change HDD or re-think DataAccessLayer logic.
