### ISSUE TITLE
implement logger

### ISSUE THREAD

**Issue by theweavrs** [hhblaze/DBreeze#26]
A logger that logs everything would be really helpful when using DBreeze. We could implement an ILogger interface and expose it to the client so that any logger can be used to write the actual messages to a file.

**Comment by hhblaze** [comment]
Logs everything?

**Comment by theweavrs** [comment]
@hhblaze Sorry, I mean a logger that logs all operations. All operations include:
1. When inserting a single record.
2. When inserting in bulk.
3. And so on.

Of course, you will say we can implement it on the client-side but I am talking about the inner logger i.e. a logger that logs the internal workings like:

```
Engine is operable. Opening transaction...
[Transaction opening logs here...]
Transaction opened.
Starting TextSearch. Keyword: "something"
and so on...
```

Of course, this will take quite a bit of time but this will help loads when debugging and finding out exactly where the transaction failed.

**Comment by hhblaze** [comment]
This will slow down the complete db, more of it, it should not be a point of a user interest, what is under the hood. If transaction fails, then there is a bug in the code or in DB. It must be fixed and db should go on further.

**Comment by theweavrs** [comment]
It is not a point of user interest but rather a point of **Developer** interest. The `Log` goes back to the developer, he looks through it and finds out where the problem and fixes it. Simple.

I wonder why all the big and state-of-the-art database and applications implement "Loggers". As for the performance issue, I think if you use a good logger the normal speed 200,000 read/writes per second (which limit a logger never reaches). A single write would take 2ms at most.

```
If transaction fails, then there is a bug in the code or in DB. It must be fixed and db should go on further.
```
You did not understand what I said. If the transaction fails, there will be something about the error in the log file. When a developer will analyze that, he will know what. **Debuggers** are not available to app users, **No Exception** is displayed to them. The app just **crashes**. To fix those bugs, it would be critical to utilize the logger.

**Comment by hhblaze** [comment]
That is the scenario:

your program actions //log it if necessary
try
DBreeze transaction is open //do nothing
program actions //log it if necessary
DBreeze actions //do nothing
program actions //log it if necessary
DBreeze actions //do nothing
DBreeze commit //do nothing
DBreeze transaction is closed //do nothing
catch(ex)
    //log definitely exception and if it is about DBreeze - show it to DBreeze dev team

program actions //log it if necessary
