### ISSUE TITLE
expose IsOperable & IsDisposed properties

### ISSUE THREAD

**Issue by theweavrs** [hhblaze/DBreeze#27]
Both of these properties would help in avoiding major bugs.

**Comment by hhblaze** [comment]
this can be done

**Comment by hhblaze** [comment]
but also there is no sense...  IsDisposed  - should not happen, 
IsOperable = false only in case if HDD fails or you something wrong with the threads is done (bug in the code). It's not normal and should be fixed. You can't go on if IsDisposed  or IsOperable

**Comment by theweavrs** [comment]
As I looked through your code, there is already such variables in place. `_isDisposed` and `_isOperable` if I am correct. To expose both of these properties will help in performing a quick check before doing any operation. 

Currently an exception is invoked crashing the app and even if we catch that exception, it is expensive (on both CPU and RAM). It would make more sense to have these properties so before any error occurs, we could backtrack and re initiate the engine.

**Comment by hhblaze** [comment]
So every time you are going make operations with DBreeze you are going to check if it's operable or disposed? What if restart can't help (HDD is damaged)?  Probably better to solve such problems in more global way - to setup your logger in case of critical mistakes to notify admins or smth.like this... 

If you have so critical up-time environment then probably you need other infrastructure with db cluster. In any case latest compilations contain:

engine.DBisOperable
engine.DBisOperableReason
engine.Disposed

https://github.com/hhblaze/DBreeze/blob/master/Deployment/bin/DBreeze_1_085_2017_0515_ULTIMATE.zip
