### ISSUE TITLE
implement Version property for version check

### ISSUE THREAD

**Issue by theweavrs** [hhblaze/DBreeze#28]
There should be a hardcoded "Version" property and another "GetVersion()" method. Basically, the use case will include checking the DB version against the hardcoded one and performing necessary updates or showing an error that an old version is being used or whatever the client wants.

**Comment by hhblaze** [comment]
you can get it from assembly

**Comment by theweavrs** [comment]
@hhblaze hmm, sounded right in mind 😆 No matter. You are right, of course.
