### ISSUE TITLE
.Net core support

### ISSUE THREAD

**Issue by VladimirAkopyan** [hhblaze/DBreeze#31]
Hello, we are talking about your DB here.   https://github.com/thangchung/awesome-dotnet-core/issues/94#issuecomment-301673582
What are your thoughts?

**Comment by hhblaze** [comment]
Hi Vladimir, actually as I know DBreeze works under .NET Standard 1.6, if you have other information - let me know.

**Comment by hhblaze** [comment]
Compiled under pure .NET Standard 1.6 from VS 2017 https://www.nuget.org/packages/DBreeze/1.85.0

**Comment by VladimirAkopyan** [comment]
cheers!

**Comment by thangchung** [comment]
Cheers!
