### ISSUE TITLE
Which DLL for Mono 5.0?

### ISSUE THREAD

**Issue by MarkuBu** [hhblaze/DBreeze#32]
Hi want to use DBreeze in Mono 5.0, but I don't know which DLL I have to use. I have 10 different DLL's here. Can you tell me, what I can use?

**Comment by hhblaze** [comment]
Hi, try the one from 
DBreeze_1_086_2017_0522_Xamarin_Android_MONO.zip
also, as an experiment, and depending upon MONO 5.0 state, can be interesting DBreeze_1_086_2017_0622_NETSTANDARD_1_6.zip

**Comment by MarkuBu** [comment]
Thanks. I try this and will report
