### ISSUE TITLE
Performance of DBreeze compared to SQLite, LevelDB or LMDB

### ISSUE THREAD

**Issue by MarkuBu** [hhblaze/DBreeze#34]
Can you say something about the performance of DBreeze compared to more common databases like SQLite, LevelDB or LMDB in the same scenario? Is DBreeze competitive?

**Comment by hhblaze** [comment]
Hi, I, personally, don't know any other database so good as their developers, but can tune up DBreeze to be very fast :) All thoughts, experience of our team and our users about it you can find in description and benchmark documents. By us DBreeze is used to be the embedded database for the servers in distributed environment for telematic solutions.
