### ISSUE TITLE
Good for logging?

### ISSUE THREAD

**Issue by stefandevo** [hhblaze/DBreeze#36]
Hi I am currently looking for an embedded solution for logging; more specific, it would need to handle the logs of incoming mobile text messages (sms) in a Callback scenario. So whenever a person sends a message to our virtual number a post is made to an url. What then happens is further business logic, but I want to save the callback info (json object) into Dbreeze. So it's insert only, and the read operations are more for diagnostics. "give me all messages between date x and date y for incoming number z". So I would need to add some indexes on number, date, etc.
So the data will only grow over time, maybe a million records per year.
Would DBreeze a good solution for this? Or should I create different tables per month for example?
Thanks for your advice!

**Comment by hhblaze** [comment]
DBreeze is perfect for such solutions, you can store in one table all data or you can split the data and store per table primary and secondary indexes for one virtual number. Of course you can quickly make range selects. Having separated table gives you ability delete it, quickly copy for analysis on the level of file system.

**Comment by stefandevo** [comment]
Thx for the feedback!
