### ISSUE TITLE
Full Text 

### ISSUE THREAD

**Issue by wcmiller3333** [hhblaze/DBreeze#39]
I have 2 full text questions.
1. How to get it to work in the first place.  In one block of code I've added names to a text name search and in another part I do the search
// the insert
tran.TextInsert("AcctTextNameSearch", item.AccountID.ToBytes(), item.FinEntity + " " + item.Contact.Name1.ToLower() + " " + item.Contact.Name2.ToLower(), "");

// the search - returns nothing although I confirmed data - the AName parameter is sent as lower 
        public void NameSearch(string AName)
        {
            using (var tran2 = engine.GetTransaction())
            {
                var tsm = tran2.TextSearch("AcctTextNameSearch");
                foreach (var w in tsm.BlockAnd(AName).GetDocumentIDs())
                {
                    Console.WriteLine(w.ToString());
                }
            }
        }

2.  I'm not familiar with how to "build" the search criteria not using the fluent style
So I'm wondering how to build multiple conditions.  So let's say I have fields to search on name, address, city, state, zip and any or all of them can be filled in.  If they are left blank I want to exclude them but if the user entered data to search, I want to add it to the text search

Thanks,
Bill

**Comment by hhblaze** [comment]
Hi, I am not near pc, so from the phone. One block can contain multiple entries that will work by the name of the block: blockAnd("Ello orld") will return all docs where both signatures are found (and condition)
On 2 question read docu

https://docs.google.com/document/pub?id=1IFkXoX3Tc2zHNAQN9EmGSXZGbQabMrWmpmVxFsLxLsw#id.ntu22plrecpi

**Comment by wcmiller3333** [comment]
Getting closer

                    byte[] key =  item.AccountID.ToBytes(); // counter.To_4_bytes_array_BigEndian(); //
                    var fin = "#" + item.FinEntity + "#";
                    tran.Insert<string, DbMJSON<Account>>("Account", item.AccountID, item);
                    tran.TextInsert("AcctTextAcctNumberSearch", key, item.AcctNumber.ToLower(), fin);
                    tran.TextInsert("AcctTextCustNumberSearch", key, item.CustomerNumber.ToLower(), fin);
                    tran.TextInsert("AcctTextNameSearch", key, item.Contact.Name1.ToLower() + " " + item.Contact.Name2.ToLower(), fin);
                    tran.TextInsert("AcctTextCitySearch", key, item.Address.City.ToLower(), fin);
                    tran.TextInsert("AcctTextStateSearch", key, item.Address.State.ToLower(), fin);
                    tran.TextInsert("AcctTextAddressSearch", key, item.Address.Address1.ToLower() + " " + item.Address.Address2.ToLower(), fin);
                    var longDesc = item.FinEntity;
                    foreach(PropertyAsset asset in item.Assets)
                    {
                        longDesc += " " + asset.Descript.ToLower();
                    }
                    tran.TextInsert("AcctTextPropertyDescSearch", key, longDesc, fin);

When I check the table counts after inserting, I get 200 in the Account table and 8 in each of the text index tables.  Is there anything I need to do differently with my key?  It is a 32 byte string converted to byte array.  Here's the code that gets 200 and then 8's
                Console.WriteLine($"ACCT RECS        {t.Count("Account")} ---");//returns 1
                Console.WriteLine($"SRCH ACCT NUMBER {t.Count("AcctTextAcctNumberSearch")} ---");//returns 1
                Console.WriteLine($"SRCH CUST NUMBER {t.Count("AcctTextCustNumberSearch")} ---");//returns 1
                Console.WriteLine($"SRCH NAME        {t.Count("AcctTextNameSearch")} ---");//returns 1
                Console.WriteLine($"SRCH CITY        {t.Count("AcctTextCitySearch")} ---");//returns 1
                Console.WriteLine($"SRCH STATE       {t.Count("AcctTextStateSearch")} ---");//returns 1
                Console.WriteLine($"SRCH ADDRESS     {t.Count("AcctTextAddressSearch")} ---");//returns 1
                Console.WriteLine($"SRCH ASSET       {t.Count("AcctTextPropertyDescSearch")} ---");//returns 1

I'm trying to figure out what I'm doing wrong so any help is greatly appreciated.

**Comment by hhblaze** [comment]
I would store all multi search parameters for the entity in one table under one key, giving unique prefix per each parameter and separating them by space e.g.
Account number unique prefix could be #an_, customer number #cn_, description. It will be one insert per entity
tran.TextInsert("AcctText", key,  "#an_"+item.AcctNumber+ " " + "cn_" + item.CustomerNumber + " " + etc other params); 

Aftet that, you can search intersecions using one and block

tsm.BlockAnd("#an_3567543 #cn_1280").GetDocumentIDs()

Or you can ask show me all accounts containing in account number "754" and part of description "good customer"

tsm.BlockAnd("754 good customer").GetDocumentIDs()

Probably here also will be returned entities that have in description "good customer" and contain in customer number "754" this must be filtered separately in memory after entity is retrived.

**Comment by hhblaze** [comment]
Count 1 is a nested table referring - don't worry, just go on to test the system. 
Don't use to lower system is case insensetive

**Comment by hhblaze** [comment]
How is it going, did you figure out the problem?

**Comment by wcmiller3333** [comment]
Not having much luck.  If I add the "Apple banana"... examples into my text search I get the same results as the example but nothing from what I've added.

And I really don't know how to use the documentID's once retrieved because they need to be converted from byte. My original keys are strings but I've tried long ints too.

How do I get the keys from the examples into something I can use.  Sorry for the trouble
block = t.TextSearch("AcctTextSearch").BlockAnd("Apple", ignoreOnEmptyParameters: true).And("", "", false, ignoreOnEmptyParameters: true);
                Console.WriteLine($"---- {block.GetDocumentIDs().Count()} ---");//returns 1
                foreach (var x in block.GetDocumentIDs())
                {
                    Console.WriteLine(x.To_Int16_BigEndian()); //32 & 64 both error
                }

**Comment by wcmiller3333** [comment]
My set of text records from another database includes 50 records with long ID's (item.SimpleID)
                    tran.TextInsert("AcctTextSearch", item.SimpleID.To_8_bytes_array_BigEndian(), "Apple Banana", "#LG1 #LG2");
I also include the 2 inserts from the example in documentation.

Yet, when I do this search, my result is 3.  I thought it should be 52.  The only difference here is that I'm using different ID's

                block = t.TextSearch("AcctTextSearch").BlockAnd("", ignoreOnEmptyParameters: true).And("", "#LG2", false, ignoreOnEmptyParameters: true);
                Console.WriteLine($"---- {block.GetDocumentIDs().Count()} ---");//returns 2

**Comment by hhblaze** [comment]
I think I need to see complete source code, to see how and what you insert,  how you fetch the data with the comments of your result expectations.

**Comment by wcmiller3333** [comment]
I got the basics working, I'll report back if I run into further issues.  Thanks.
