### ISSUE TITLE
Document Growth

### ISSUE THREAD

**Issue by wcmiller3333** [hhblaze/DBreeze#40]
Is there a way to allow for document growth? I'm designing models and determining best way to go.
1. Either to not worry about growth of a document as it is written to new location and then copy/reduce the database periodically
or
2. Separate the document detail lines from the document but then lose the fetch of a whole document in one pass.

Any experience on which provides best performance? Or is there a "best practice"?

**Comment by hhblaze** [comment]
While text search DBreeze doesn't store the document itself only unique words together with the reference between them and supplied external document id. 
You can store the doc also in DBreeze using tran.InsertDataBlock technique (compression is out of scope)

**Comment by wcmiller3333** [comment]
I meant more of JSON documents, because I will have classes that contain lists that grow, this is not in reference to text search but just the use of space in the database itself when a json document grows, it will need to be rewritten to the end of the data because it won't fit in the old slot.  Is there any cushion of space to allow the existing spot to be reused? Like a block size?

**Comment by wcmiller3333** [comment]
I guess it is just a matter of preference.
