### ISSUE TITLE
DBreeze single Database File

### ISSUE THREAD

**Issue by Arashz22** [hhblaze/DBreeze#48]
Hi Dear Developer
I want to save video file to a database
finally after testing many databases, I found DBreeze as the most fastest.
but I have a question.
Is it possible to have one database file like SQLite or LiteDb ? or copy other files to a temp folder ?
my DBreeze DB have more than one file as I've attached
![1](https://user-images.githubusercontent.com/10775073/45253786-5e0f9500-b382-11e8-9509-8d8862092891.jpg)
.

**Comment by hhblaze** [comment]
Hi, Dbreeze needs many files, to be compact, fast and flexible. I recommend to store video files in file system and only meta information about these files (for fast search of video file names) in database.
thank you for the interest

**Comment by Arashz22** [comment]
Yes you are right but i want to encrypt my video file and save some bookmark(Time) for video.
and sell videos as single files.
and the videos will be played just with my own player.
do you have any other suggestion ?

**Comment by hhblaze** [comment]
Zip file, may be

**Comment by sgf** [comment]
For document databases, 2 files are generally very good when WAL is enabled. One problem with DBreezed is that it has too many files.
