### ISSUE TITLE
TextSearch bug

### ISSUE THREAD

**Issue by ruijiexie** [hhblaze/DBreeze#56]
Quick start guide . Songs library
Only change ArtistName = "The Beatles" to ArtistName = "周杰伦" 

t.TextSearch("SongsText").Block("周杰伦")  can't find anything

Textsearch need to support for encoding

**Comment by hhblaze** [comment]
Utf8 is supported

**Comment by hhblaze** [comment]
If u have symbol encoding wider than that, please, make your own text transformations to Utf8 scheme, before putting it to the search algorithm

**Comment by ruijiexie** [comment]
DBreeze.Utils.CustomSerializator.ByteArraySerializator = (object o) => { return NetJSON.NetJSON.Serialize(o).To_UTF8Bytes(); };
DBreeze.Utils.CustomSerializator.ByteArrayDeSerializator = (byte[] bt, Type t) => { return NetJSON.NetJSON.Deserialize(t, bt.UTF8_GetString()); };

save utf8 encoding , but t.TextSearch("SongsText").Block("jazz")   Block parameter  is not support utf8

**Comment by hhblaze** [comment]
Will try to understand what you mean. But the best would be to provide a code example.

**Comment by hhblaze** [comment]
Show in the code how you store data and how you search. I must sure it is done correctly. We internally got a software translation portal based on Dbreeze Text Search, minimum 8 languages under support. All works since now.

**Comment by hhblaze** [comment]
So, it works even with those hieroglyphs:

![image](https://user-images.githubusercontent.com/486781/64521550-7cdb9b00-d2f8-11e9-99a0-1e232499386b.png)
