### ISSUE TITLE
DBreeze sorts by ID

### ISSUE THREAD

**Issue by Hadaa12** [hhblaze/DBreeze#58]
Hi DBreeze team,
Im very new to dbreeze world and i found it simple, fast and reliable database.
Im trying to store users chats, but the problem im facing is that dbreeze seems to sort them my id(ID i used) which i dnt want.
Here is the code i used to query using LINQPAD
```
var db = new DBreeze.DBreezeEngine(@"File");
	using(var tr = db.GetTransaction())
	{
	var s = tr.SelectForward<string, DbMJSON<Message>>("ToAli").Select(x=>x.Value.Get).Dump();

	}
	db.Dispose();
```

![image](https://user-images.githubusercontent.com/55669013/65393773-e2666780-dd8d-11e9-8010-f7335c3e1ed7.png)

I dont know if approaching in a wrong way, it is sorting by ID. I want the message to be the way they r inserted without any sorting.

Am i doing in a wrong approach? what to do?

**Comment by hhblaze** [comment]
Hi, you should really start from the docu. DBreeze automatically sorts by inserted key, so if you want records to be sorted by insert sequence use as a key growing up integer 1,2,3. In your case you will need probably minimum two indexes, one is to assure the sorting by adding sequence, second to search by MessageID: use object DBreeze for that. Example is [here](https://github.com/hhblaze/DBreeze/wiki/Quick-start-guide.-Songs-library)

**Comment by Hadaa12** [comment]
Thank you very much. 
I have one more issue. Should I comment here or create new issue?

**Comment by hhblaze** [comment]
> Thank you very much.
> I have one more issue. Should I comment here or create new issue?

As you wish

**Comment by Hadaa12** [comment]
Thank you. I will create new issue, it may help someone else who have same problem.
