### ISSUE TITLE
Biser Objectifies classes using different namespace than DBreeze's version

### ISSUE THREAD

**Issue by robotron2084** [hhblaze/DBreeze#63]
There is a slight incompatibility between the version of Biser shipped inside DBreeze and that used by BiserObjectify.

To reproduce:

1. Create `_Biser.cs` files via `Objectify`.
2. Add these files to your project that does not contain Biser.
3. Observe that the `_Biser.cs` files do not compile.
4. Add `using DBreeze.Utils;` to the `_Biser.cs` files.
5. Observe that the files now compile successfully. 

Expected Results:
When creating serialization stubs for classes, that they are compatible with the version of Biser that ships with DBreeze without requiring manually modifying the files.

**Comment by hhblaze** [comment]
Yes, probably will enter a new parameter smth. like "generate for DBreeze".

**Comment by hhblaze** [comment]
Grab new BiserObjectify from Nuget and re-generated classes due to the instruction:

![image](https://user-images.githubusercontent.com/486781/103691640-c8f32a00-4f96-11eb-83ba-fd8d513dbba2.png)

**Comment by robotron2084** [comment]
Pulled latest and it does work as expected. I'm currently using this in a Unity project and it is yelling at me about inconsistent line endings. I'm not sure if that's a new thing that has been introduced in this release. I may look into it and send you a PR.

**Comment by hhblaze** [comment]
I will check it

**Comment by hhblaze** [comment]
Line endings are fixed in BiserObjectify 1.7.0 (grab from NuGet)
