### ISSUE TITLE
.net core 5

### ISSUE THREAD

**Issue by PSanilP** [hhblaze/DBreeze#66]
Hi, 
I have been following your project since 2014 and have used in a couple of apps.
Now we have most of our core into JS and .netCore 5
I tried to compile your .net 1.0 and it didnt. Any chance of fixing it? 
![Capture](https://user-images.githubusercontent.com/86600502/123620126-2c556a80-d80a-11eb-87ca-40618eda4fbe.PNG)

**Comment by hhblaze** [comment]
Project is compiled to be compatible with .NET5 (.NET Standard) inside of NuGet package.
If you want to recompile it yourself, just make a copy of .NET standard project (where all files are correctly linked)

**Comment by PSanilP** [comment]
There are missing files even in .Net Standard project

**Comment by hhblaze** [comment]
![image](https://user-images.githubusercontent.com/486781/123631442-0da9a080-d817-11eb-9f74-a841f321fc35.png)

**Comment by hhblaze** [comment]
They are linked in original solution
