### ISSUE TITLE
TextSearch Tables still contains internal/external references, after using TextRemoveAll

### ISSUE THREAD

**Issue by Drofzz** [hhblaze/DBreeze#69]
I don't know if this is intentional.

However, TextSearchTables still contains old refs in e2i, i2e and words after using TextRemoveAll.

by using 

```csharp
Transaction.TextInsert(DataTablesEmails, docId, fullMatchWords: authorEmail); 
```

it will add internal and external document ids.

after using 

```csharp
Transaction.TextRemoveAll(DataTableEmails, docId);
```

it still saves the internal and external ids, even the words are still in the Words table.

this seems to be a bug, as there is no other way to clean up the tables, other than doing it manually.

i was able to debug by accessing the TableSearchTable manually.

```csharp
using var t = engine.GetTransaction(eTransactionTablesLockTypes.SHARED);

tbWords = t.SelectTable<byte>(DataTransaction.DataTableEmails, 20, 0);
tbWords.ValuesLazyLoadingIsOn = false;
Words = tbWords.SelectDictionary<string, byte[]>();

tbBlocks = t.SelectTable<byte>(DataTransaction.DataTableEmails, 10, 0);
tbBlocks.ValuesLazyLoadingIsOn = false;
Blocks = tbBlocks.SelectDictionary<uint, byte[]>();

tbsrch = t.SelectTable<byte>(DataTransaction.DataTableEmails, 3, 0);
tbsrch.ValuesLazyLoadingIsOn = false;
Searchables = tbsrch.SelectDictionary<byte[], byte[]>();

tbi2e = t.SelectTable<byte>(DataTransaction.DataTableEmails, 2, 0);
tbi2e.ValuesLazyLoadingIsOn = false;
Internals = tbi2e.SelectDictionary<int, byte[]>();

tbe2i = t.SelectTable<byte>(DataTransaction.DataTableEmails, 1, 0);
tbe2i.ValuesLazyLoadingIsOn = false;
Externals = tbe2i.SelectDictionary<byte[], int>();
```

**Comment by hhblaze** [comment]
Hi, I am not sure that I understood you correctly, so will describe the logic briefly.
We can have document Nr 1 with the text "hello world". We can update this document with the word "hello".
This document will not be searched any more by the word "world". 
Or we can update this document with the word set "hello world again" - afterwards we can search this document by these 3 words.
TextRemoveAll updates the existing document telling that there is no more words. 
Document Nr itself is left in the system and can be filled up with new words again.

**Comment by hhblaze** [comment]
Ok, clear, - everything is alright. 
TextRemoveAll doesn't delete already created document IDs, but detaches words bound to that document ID.
As many documents you will insert as more space it will reside, but mostly ID takes only several bytes per inserted document. 

More of it, in the whole DBreeze "delete / remove" doesn't mean removing data from the file, but the logical remove of the references. 
The physical remove from the table is also possible with a flag, but only when you delete all inserted data from the table - read in docu.

**Comment by hhblaze** [comment]
I must say that in our cases mostly we never delete anything from TextSearchSubSystem (TSSS ) when removing the document or marking the document as deleted. 
Sometimes document (or searchable object) stores its legacy in different TSSS, e.g. there is a forum bound to the object and this generic forum solution uses its own TSSS. We don't delete all bindings to the deleted document in the complete system when removing it.
Those subsystems go on to return deleted document ID, but handlers of the higher level understand that returned by TSSS document is already removed and skip propagating such document further.
We resolve it on the other level. 
Though, when it is really necessary, it is possible to remove that external docID reference directly from the concrete TSSS - that may economize "one select" on a higher level that uses DBreeze. 
Currently, until the document is not detached from the words, its ID will be in any case found, checked with the internalID-externalID mapper and returned to the DBreeze consumer - on the upper level. 
We can add a new function like "TextDeleteDocument" and fix that mapper: if link between internalID and externalID is not found then skip returning such ID on the higher level. 
Actually we gain not much, but all depends upon the use case - write it down here, if you really need that.

**Comment by Drofzz** [comment]
thanks for the tip, I've been digging through the TextSearchTable system all night, as it really gives a useful insight.

it makes it a little easier to get an insight into the TextSearchTable... sadly this documentation is only in the source-code comments 

```csharp
            tbWords = t.SelectTable<byte>(DataTransaction.DataTableEmails, 20, 0);
            Words = tbWords.SelectDictionary<string, byte[]>().Select(kv =>
            {
                uint blockid = kv.Value.Substring(0, 4).To_UInt32_BigEndian();
                uint numberInBlock = kv.Value.Substring(4, 4).To_UInt32_BigEndian();
                return new KeyValuePair<string, (uint BlockId, uint NumberInBlock)>(kv.Key, (blockid, numberInBlock));
            }).ToDictionary(kv => kv.Key, kv => kv.Value);
            tbBlocks = t.SelectTable<byte>(DataTransaction.DataTableEmails, 10, 0);
            Blocks = tbBlocks.SelectDictionary<uint, byte[]>().Select(block =>
            {
                var blocksize = block.Value.Substring(0, 4).To_Int32_BigEndian();
                var data_block = new Dictionary<uint, byte[]>();
                if(blocksize > 0)
                {
                    var btBlock = block.Value.Substring(4, blocksize);
                    btBlock.Decode_DICT_PROTO_UINT_BYTEARRAY(data_block, Compression.eCompressionMethod.Gzip);
                }
                return new KeyValuePair<uint, Dictionary<uint, byte[]>>(block.Key, data_block.Select(kv =>
                {
                    var bt = kv.Value;
                    return new KeyValuePair<uint, byte[]>(kv.Key, bt);
                }).ToDictionary(kv => kv.Key, kv => kv.Value));
            }).ToDictionary(kv => kv.Key, kv => kv.Value);
            tbsrch = t.SelectTable<byte>(DataTransaction.DataTableEmails, 3, 0);
            Searchables = tbsrch.SelectDictionary<byte[], byte[]>().Select(kv => {
                var key = kv.Key.Substring(0, 4).To_Int32_BigEndian();
                var value = kv.Value.GZip_Decompress().ToUTF8String();
                return new KeyValuePair<int, string>(key, value);
            }).ToDictionary(kv => kv.Key, kv => kv.Value);
            tbi2e = t.SelectTable<byte>(DataTransaction.DataTableEmails, 2, 0);
            Internals = tbi2e.SelectDictionary<int, byte[]>();
            tbe2i = t.SelectTable<byte>(DataTransaction.DataTableEmails, 1, 0);
            Externals = tbe2i.SelectDictionary<byte[], int>();
```
