### ISSUE TITLE
Memory mode insert slower than writes on disk

### ISSUE THREAD

**Issue by ToxyMao** [hhblaze/DBreeze#72]
Hello, I use both versions of engine: memory and disk.
When I write objects to memory engine, it is slower every batch insert.
Inserts in disk engine is faster, and speed of write don't changes with every batch insert.
As far as I understand, this is due to the use of RAM.
Maybe there is some solution?
docu have not enough information about memory mode

**Comment by hhblaze** [comment]
It may happen, because of different algorithms of writing and today we got fast M.2. 
May be once it would be nice to re-write the code part answering for the byte arrays management with the new .NET 6 techniques. 
But, I guess, even now it is not MUCH slower.
