### ISSUE TITLE
Database  insert speed 

### ISSUE THREAD

**Issue by ToxyMao** [hhblaze/DBreeze#73]
HelloThe database object has 6 indices. The client inserts approximately 15k objects into the base in 5 seconds. This is a very good speed for me. But when the database began to have a 10GB size, the time for the insert of those 15k objects became about 80 seconds. After 10 minutes, the insert speed again became 5 seconds. Does the database sometimes recalculate indexes?
I did tests several times, and every time there was such a situation.
Thank you

**Comment by ToxyMao** [comment]
In features I have found: Liana-Trie indexing technology. Database indexes (keys) never need to be defragmented. Speed of insert/update/remove operations doesn't change during the time. 
I use speedUpdate=true flag when objects insert

**Comment by ToxyMao** [comment]
I have check pidstat on linux, it says that my process in that situation have I/O disk read speed about 5bm/sec, and write speed about 200kb/sec

**Comment by hhblaze** [comment]
- "Does the database sometimes recalculate indexes?"
- No

If you want go deeper, you have to make more personal "scientific" experiments. They will have to cover performance monitors of database functions, the nature of inserting keys and methods of inserts. When you see bottlenecks, you may refer to DBreeze approaches and your infrastructure.

**Comment by hhblaze** [comment]
You could also publish your long-running code, may be it will be also much clear
