### ISSUE TITLE
Vector Simillarity search unexpected results

### ISSUE THREAD

**Issue by grinay** [hhblaze/DBreeze#75]
Hi guys. Thanks for your efforts to work on DBreeze, was looking for embedding database which support vectors, and you the only one who is actually working on it for C#. Was happy to find you. 
I started testing product yesterday, made local embedding with few models bge-small-en, bge-base-en-v1.5.
Started testing and few questions appears:
1. How to get the similarity score after search with VectorsSearchSimilar as it only returns key, which I'm using to resolve original document. 
2. How the vector similarity works under the hood, as it gives me some unexpected result here is the examples:
Test sample are: 
"The TV isn't working. There is no electricity." 
"The sun is shining, and the weather is awesome."
and we search with the question:
"Which one is good?"
With the model "bge-small-en" result looks correct search result have proper top 2 k results order:
First sentense more positive
Name: The sun is shining, and the weather is awesome.
Name: The TV isn't working. There is no electricity.

And the calculation of cosine similarity against each sentence with question are:
Cosine similarity score: 61,963394102426 (The sun is shining, and the weather is awesome.)
Cosine similarity score: 59,239681908562 (The TV isn't working. There is no electricity.)

When using model bge-base-en-v1.5:
The output are incorrect, and negative sentence is on top of the results:

Name: The TV isn't working. There is no electricity.
Name: The sun is shining, and the weather is awesome.

But the cosine similarity calculated shown that first sentence has way higher score with this model: 
Cosine similarity score: 54,020624055590 (The sun is shining, and the weather is awesome.)
Cosine similarity score: 41,156959018150 (The TV isn't working. There is no electricity.)
Please advise on the internal and what can be tuned, or maybe fixed to have expected results, I think result must be the same as with the bge-small-en model as cosine similarity score in both cases are correct. 
here is how cosine similarity calculated on my end 
```csharp
              if (corpus.Length != query.Length)
                {
                    return 0;
                }

                double dotProduct = 0.0;
                double magnitude1 = 0.0;
                double magnitude2 = 0.0;

                for (int i = 0; i < corpus.Length; i++)
                {
                    dotProduct += corpus[i] * query[i];
                    magnitude1 += Math.Pow(corpus[i], 2);
                    magnitude2 += Math.Pow(query[i], 2);
                }

                magnitude1 = Math.Sqrt(magnitude1);
                magnitude2 = Math.Sqrt(magnitude2);

                if (magnitude1 == 0.0 || magnitude2 == 0.0)
                {
                    throw new ArgumentException
                        ("embedding must not have zero magnitude.");
                }

                double cosineSimilarity = dotProduct / (magnitude1 * magnitude2);

                return cosineSimilarity;
```

**Comment by grinay** [comment]
Sorry. Was my mistake. After I normilized vectors everything works as expected.

**Comment by hhblaze** [comment]
Ok, the distance is calculated here [https://github.com/hhblaze/DBreeze/blob/master/DBreeze.Net5/VectorLayer/VectorMath.cs](https://github.com/hhblaze/DBreeze/blob/master/DBreeze.Net5/VectorLayer/VectorMath.cs) 
In function Distance_SIMDForUnits

**Comment by Haoming02** [comment]
> After I normilized vectors everything works as expected

Hello, can you explain which method you used?

I tried normalizing to both `[0, 1]` and `[-1, 1]`, as well as `mean` with `std` of `1`. 
But all of them seem to keep giving me the same result, regardless what my query is...
