### ISSUE TITLE
vector database search slow

### ISSUE THREAD

**Issue by zhouzhuli** [hhblaze/DBreeze#77]
When performing a search operation in a vector database with approximately 1,000 entries, it takes about ten seconds to get results on a mobile phone.

The code is as follows:
public void SearchDatas()
    {
        //Those for tests....
        double[] questionEmbedding = OpenAIEmb.embedding; // For testing and to avoid delays, it has already been obtained

        //-show top 3 most relevant answers
        using (var tran = Program.DBEngine.GetTransaction())
        {
            tran.ValuesLazyLoadingIsOn = false; //to read key already with value

            var res = tran.VectorsSearchSimilar(table_vertor, questionEmbedding, 3);

            foreach (var el in res)
            {
                var rowDoc = tran.Select<byte[], string>(table_value, 2.ToIndex(el));
                Debug.Log(rowDoc.Value);
            }
        }
    }

**Comment by zhouzhuli** [comment]
When performing only vector search operations, that is, calling the VectorsSearchSimilar method, there is basically no delay. The delay is caused by this part of the code:
foreach (var el in res)
{
    var rowDoc = tran.Select<byte[], string>(table_value, 2.ToIndex(el));
}

**Comment by hhblaze** [comment]
That is normally a very standard and a very fast operation. May be you should remove Debug.Log  or so...

**Comment by hhblaze** [comment]
Also, if you are debugging on the mobile from VS - there is an extra connectivity layer.

**Comment by hhblaze** [comment]
try installed Release(d) software, right on the phone

**Comment by zhouzhuli** [comment]
> try installed Release(d) software, right on the phone

//Like this, is ok
using (var tran = Program.DBEngine.GetTransaction())
        {
            tran.ValuesLazyLoadingIsOn = false; //to read key already with value

            var res = tran.VectorsSearchSimilar(table_vertor, questionEmbedding, 3);

            //foreach (var el in res)
            //{

            //}
        }
        
        //That will be very slow
        using (var tran = Program.DBEngine.GetTransaction())
        {
            tran.ValuesLazyLoadingIsOn = false; //to read key already with value

            var res = tran.VectorsSearchSimilar(table_vertor, questionEmbedding, 3);

            foreach (var el in res)
            {

            }
        }
        
        I don't know why the loop is causing this result. I may need more test. I'll upload the results later.

**Comment by hhblaze** [comment]
If you can create a VS test project already filled up with embeddings (the whole DBreeze folder filled up with your embeddings), and supply it as a Zip, so I could also take a look on the real data and workflow - would be helpful.

**Comment by hhblaze** [comment]
> > try installed Release(d) software, right on the phone
> 
> //Like this, is ok using (var tran = Program.DBEngine.GetTransaction()) { tran.ValuesLazyLoadingIsOn = false; //to read key already with value
> 
> ```
>         var res = tran.VectorsSearchSimilar(table_vertor, questionEmbedding, 3);
> 
>         //foreach (var el in res)
>         //{
> 
>         //}
>     }
>     
>     //That will be very slow
>     using (var tran = Program.DBEngine.GetTransaction())
>     {
>         tran.ValuesLazyLoadingIsOn = false; //to read key already with value
> 
>         var res = tran.VectorsSearchSimilar(table_vertor, questionEmbedding, 3);
> 
>         foreach (var el in res)
>         {
> 
>         }
>     }
>     
>     I don't know why the loop is causing this result. I may need more test. I'll upload the results later.
> ```
VectorsSearchSimilar returns enumerable, so if somethings causes it is not a loop itself, but VectorsSearchSimilar

**Comment by hhblaze** [comment]
I would run it locally with your data on my PC first

**Comment by zhouzhuli** [comment]
Well, it should be the problem with the VectorsSearchSimilar part. Since I am developing in Unity, I need to remake the pure VS project, which may take some time.

**Comment by hhblaze** [comment]
We have tested it on many different records - no problem....so your data could be for a good help.

**Comment by hhblaze** [comment]
Actually what I will need: database, may be code for the insert and select and byte[] of your query embedding - would be enough

**Comment by zhouzhuli** [comment]
[DBVector.zip](https://github.com/user-attachments/files/15915609/DBVector.zip)
This is my database data, can you use it? The data in it is obtained and filled from FurnitureV1withEmbeddings.json in the sample folder

**Comment by zhouzhuli** [comment]
Then we call a simple search function, which is the following code:
The content of OpenAIEmb.embedding is the embedding of the first data obtained from FurnitureV1withEmbeddings.json
I also tried it on a computer, and there were some lags.

public void SearchDatas2()
{
    //Those for tests....
    double[] questionEmbedding = OpenAIEmb.embedding;

    //-show top 3 most relevant answers
    using (var tran = Program.DBEngine.GetTransaction())
    {
        tran.ValuesLazyLoadingIsOn = false; //to read key already with value

        var res = tran.VectorsSearchSimilar(table_vertor, questionEmbedding, 3);

        foreach (var el in res)
        {
            var rowDoc = tran.Select<byte[], string>(table_value, 2.ToIndex(el));
        }
    }
}

**Comment by hhblaze** [comment]
I will check

**Comment by zhouzhuli** [comment]
[VectorDataBase.zip](https://github.com/user-attachments/files/15922685/VectorDataBase.zip)

This is a VS project I did. When the data is relatively small, the vector search matching speed is very fast, and 1,000 data has no significant impact. However, when the data reaches 50,000, you will feel obvious lag, and the memory and CPU will also be affected. This impact is particularly obvious on mobile phones, which may cause a long wait.

**Comment by zhouzhuli** [comment]
> nice, will check (Did you put already those 50K right in DBVector.zip?)

Not yet. Due to size issues, the database cannot be uploaded. You can directly run the sample code to insert these data.

**Comment by hhblaze** [comment]
That is what I see for now
https://www.youtube.com/watch?v=Si9q3BDBOdw

**Comment by hhblaze** [comment]
And performing search with a filled up DB from the USB (3.0) Flash drive
https://www.youtube.com/watch?v=n7n1U_ZODrg

**Comment by hhblaze** [comment]
DBreeze layer was not tested on the mobile. 
But DBreeze itself works on many mobile projects only in our company environment. 
Will try on the next week via Xamarin - need different environment.

**Comment by hhblaze** [comment]
![image](https://github.com/hhblaze/DBreeze/assets/486781/60900d04-3ea4-4ff6-afe5-56f3056c9578)

**Comment by hhblaze** [comment]
![image](https://github.com/hhblaze/DBreeze/assets/486781/dae5a060-9429-4461-92eb-c8cb13dd5cce)

**Comment by zhouzhuli** [comment]
OK, I will try it and will post any information I have. If there are any results from the mobile phone test next week, I hope you can inform me. Thank you!

**Comment by hhblaze** [comment]
I made some experiments over MAUI .NET on Samsung S21 with .NET5 DBreeze.dll.
All tests only in RELEASE mode

5000 vectors inserted - DB size already was about 1.5 GB - vectors are different (you were inserting the same vectors again and again). 

Changes in code: 
- each 1000 inserts - new transaction. 
- Generate random vectors with
```C#
static double[] GetRandomEmbedding()
{
    int size = 1536;
    Random random = new Random();
    double[] randomArray = new double[size];

    for (int i = 0; i < size; i++)
    {
        randomArray[i] = random.NextDouble();
    }
    return randomArray;
    // Now you can use the randomArray
}
```

Search speed is under 20ms.

Resuming:
- test in RELEASE mode
- 5000 vectors can already be a 5000 documents (not a vector per a sentence, but a vector per one document or several vectors per one document) that already is for mobile too much - use server side.
- you can create many vector tables (depends upon logic)

I don't see necessity for the update for now.

**Comment by zhouzhuli** [comment]
I don't see any .NET5 DBreeze.dll. The version of the DBreeze library I imported using Nuget in Unity is DBreeze.1.116.2024.527, which contains netstandard2.1 libraries. I packaged it with Unity and installed it on my phone. No matter which device I use, it is very slow when searching. Can you send me your VS project and APK?

**Comment by hhblaze** [comment]
For me a bigger problem makes an insert on the phone, but this I hope to optimize. Any DBreeze from Nuget is OK, MAUI uses .NET5 as I see. https://filetransfer.io/data-package/GdkJ0uDj#link

**Comment by hhblaze** [comment]
Here is https://github.com/hhblaze/DBreeze/tree/master/Deployment/bin/NETSTANDARD2_1  v 1.117 (let's say pre-release). 
MAUI https://filetransfer.io/data-package/6wJlJCjL#link

![image](https://github.com/hhblaze/DBreeze/assets/486781/79bc2904-1e22-4a75-b670-84d91d0ddb9b)

Results: 
Insert of 50000 vectors of 1536 bytes - 127 seconds
Select - 151 ms
Storage - 453 MB

![image](https://github.com/hhblaze/DBreeze/assets/486781/f7c4413a-1ac9-4b4d-8119-597bf5e80d7d)
![image](https://github.com/hhblaze/DBreeze/assets/486781/4d8978be-f64c-474a-a6fe-b2b4e7b9f9bd)



Later will be in NuGet.

**Comment by zhouzhuli** [comment]
After I added the VectorLayerConfig = new DBreezeConfiguration.VectorlayerConfiguration() { Dense = 100 } parameter in Unity, an error always occurs when inserting data. The error is as follows:
InvalidOperationException: Collection was modified; enumeration operation may not execute.
System.Collections.Generic.Dictionary`2+Enumerator[TKey,TValue].MoveNext () (at <f843d796055e4deaa447e7ba073cff5f>:0)
DBreeze.VectorLayer.Clustering.KMeansCluster (System.Collections.Generic.List`1[T] data, System.Int32 k) (at <84f6fa9e10cc4523a285e4cdacdb25f2>:0)
DBreeze.VectorLayer.Vectors.RestructGraph () (at <84f6fa9e10cc4523a285e4cdacdb25f2>:0)
DBreeze.VectorLayer.Vectors.AddVectors (System.Collections.Generic.IReadOnlyDictionary`2[TKey,TValue] vectors) (at <84f6fa9e10cc4523a285e4cdacdb25f2>:0)
DBreeze.Transactions.Transaction.VectorsInsert (System.String tableName, System.Collections.Generic.IReadOnlyDictionary`2[TKey,TValue] vectors, System.Boolean deferredIndexing) (at <84f6fa9e10cc4523a285e4cdacdb25f2>:0)
TestSpeed2.Store_String_Vectors () (at Assets/Scripts/TestSpeed2.cs:70)

Below is my code:
/// <summary>
    /// 
    /// </summary>
    static void InitDB()
    {
        string DBPath = PathToDatabase;
        DBreezeConfiguration conf = new DBreezeConfiguration()
        {
            DBreezeDataFolderName = DBPath,
            Storage = DBreezeConfiguration.eStorage.DISK,
            VectorLayerConfig = new DBreezeConfiguration.VectorlayerConfiguration() { Dense = 100 }
        };
        conf.AlternativeTablesLocations.Add("mem_*", String.Empty);
        DBEngine = new DBreezeEngine(conf);

        DBreeze.Utils.CustomSerializator.ByteArraySerializator = TesterNet6.ProtobufExtension.SerializeProtobuf;
        DBreeze.Utils.CustomSerializator.ByteArrayDeSerializator = TesterNet6.ProtobufExtension.DeserializeProtobuf;

        Debug.Log("Init Success");
    }


    static string tableVector = "tableVector"; //Vector Table
    int idCnt = 0;
    public void Store_String_Vectors()
    {
        Debug.Log("Store_String_Vectors Start " + Time.time);

        //-such format will be inserted into VectorTable, Key is exernal documentID, value is vector itself
        Dictionary<byte[], double[]> vectorsToInsert = new Dictionary<byte[], double[]>();
        using (var tran = DBEngine.GetTransaction())
        {
            //-sync of Doctable and vector table for searching docs
            tran.SynchronizeTables(tableVector);

            //Loop and insert 10 times the same data
            for (int i = 0; i < 50; i++)
            {
                idCnt++;

                vectorsToInsert.Add(idCnt.To_4_bytes_array_BigEndian(), GetRandomEmbedding());
            }

            //-storing documents as vectors (with/without deferred indexing) 
            if (vectorsToInsert.Count > 0)
            {
                //-in case of big quantity of vectors, use deferredIndexing: true (to run computation in the background)
                tran.VectorsInsert(tableVector, vectorsToInsert, deferredIndexing: false);
            }

            tran.Commit();

            Debug.Log("Vector Count == " + tran.Count(tableVector));
        }

        Debug.Log("Store_String_Vectors End " + Time.time);
    }

**Comment by hhblaze** [comment]
And on PC? I have bound to MAUI .NETSTANDARD2.1 DLL, with the Dense = 100, your code (inserting 50 vectors), insert in empty Database - no problems on Samsung mobile. The same on PC.

**Comment by zhouzhuli** [comment]
Yes, there are problems on both the phone and the computer. I tested it in the Unity environment. There seems to be no problem with VS. I have been trying to figure out where the problem lies. It may be related to threads or something. This is also a challenge for me.

**Comment by zhouzhuli** [comment]
I also tried the project you sent me. I also tested it on a relatively backward mobile phone. There is indeed no problem. The vector search is also very fast. It’s just that the version I made with Unity is not good. The search is still very slow. At the same time, there are still the problems I mentioned above. I think I need to study it in depth.

**Comment by hhblaze** [comment]
I have no problem neither on PC nor on mobile with your 50 vectors insert https://www.youtube.com/watch?v=OO5-Cq-NNcs

**Comment by hhblaze** [comment]
MAUI in DEBUG - also slower, RELEASE - very fast...this is clear why.... so may be you should move Unity to RELEASE mode.... I have no experience with the Unity.

**Comment by hhblaze** [comment]
Also...try the empty database, for the clear experiment

**Comment by hhblaze** [comment]
Actually, I think I am ready with DBreeze release 117, that's is a bit optimizing storage of the vector table while insert, 
but there were no changes in logic itself or changes in the Select code.

I will give a bit time before the release (may be we got something new :) and then also will close the ticket.

**Comment by hhblaze** [comment]
This Dense also doesn't help so much, but for mobiles may be more optimal solution from the memory point of view

**Comment by zhouzhuli** [comment]
Ok, this should be a problem with Unity itself, thanks for your help

**Comment by zhouzhuli** [comment]
I used to use the library and imported it directly. Now if I want to use the source code, which folders should I import? I used .NETSTANDARD2.1 DLL before.

**Comment by hhblaze** [comment]
![image](https://github.com/hhblaze/DBreeze/assets/486781/1ba803f6-a974-40c9-a608-76bc793f2294)

**Comment by zhouzhuli** [comment]
I found the error in Unity. In the DBreeze.VectorLayer.Clustering file, there is a piece of code in the KMeansCluster method:
foreach (var cluster in clusters)
{
double[] newCentroid = new double[data[0].Length];

foreach (var dataIndex in cluster.Value.Item2)
{
for (int j = 0; j < data[dataIndex].Length; j++)
newCentroid[j] += data[dataIndex][j];
}

for (int j = 0; j < newCentroid.Length; j++)
{
if (cluster.Value.Item2.Count > 0)
newCentroid[j] /= cluster.Value.Item2.Count;
}

if (!ArraysEqual(cluster.Value.Item1, newCentroid))
{
centroidsChanged = true;
clusters[cluster.Key] = (newCentroid, cluster.Value.Item2);
}
}
In Visual Studio or any other environment, attempting to modify a collection (such as an array, list, dictionary, etc.) while iterating over it (enumerating it) is inherently disallowed. This is because such an operation would violate the state consistency of the collection and the safety of the enumerator.

Here is the modified code:
List<int> keys = new List<int>(clusters.Keys);
for (int index = 0; index < keys.Count; index++)
{
int key = keys[index];
double[] newCentroid = new double[data[0].Length];

foreach (var dataIndex in clusters[key].Item2)
{
for (int j = 0; j < data[dataIndex].Length; j++)
{
newCentroid[j] += data[dataIndex][j];
}
}

for (int j = 0; j < newCentroid.Length; j++)
{
if (clusters[key].Item2.Count > 0)
{
newCentroid[j] /= clusters[key].Item2.Count;
}
}

if (!ArraysEqual(clusters[key].Item1, newCentroid))
{
centroidsChanged = true;
clusters[key] = (newCentroid, clusters[key].Item2);
}
}

**Comment by zhouzhuli** [comment]
Can you help me make a .NETSTANDARD2.1 DLL with the modified code? Because I am using the source code now, I use the vector search on my phone and computer very quickly. I want to know if it is the library problem, or if the Dense parameter you added last time solved the speed problem on Unity. I can't use the Dense parameter with the original library because of the problem of modifying the collection when traversing.

**Comment by hhblaze** [comment]
Oh yes, that part of code was optimized for me by Mistral! I even didn't notice that...very good! Hold it 
![image](https://github.com/hhblaze/DBreeze/assets/486781/8d72af4e-0152-4216-9b78-68d137694869)

**Comment by hhblaze** [comment]
if you report that all is good, I will place a new 117 release also in Nuget

**Comment by zhouzhuli** [comment]
I tested it many times, and the iteration error problem has been solved and will not appear again, but when using the DLL, the search and insertion speed is still very slow, which may be related to Unity. I can only use the source code at present. Fortunately, I finally got a solution. Thank you for your help, good luck!

**Comment by hhblaze** [comment]
Can you compile .NETSTANDARD source to DBreeze.dll via UNITY somehow?

**Comment by hhblaze** [comment]
I got a special machine where different environments are installed (from .NET Framework 3.5 and so on), so, if it works, I could repeat that trick with the Unity, of course if I don't need to pay for it (otherwise such DLL must produce someone with an installed Unity).

**Comment by zhouzhuli** [comment]
Currently, Unity does not support this operation. The libraries used before were all made through VS. Or I can try to make a DLL library for Unity with VS and the source code I am using now, and then check its efficiency. I don’t know if it is different from what you made. I will tell you when there is a result.
