### ISSUE TITLE
Remove duplicates

### ISSUE THREAD

**Issue by HakanL** [hhblaze/DBreeze#9]
It seems that all source files are duplicated into DBreeze.UWP and NETCore folders. It would probably be better to link the files, hard to maintain multiple copies, risky and error-prone.

**Comment by HakanL** [comment]
?

**Comment by hhblaze** [comment]
I will not do it for now, I find my way better

**Comment by HakanL** [comment]
Ok, that's fine, your project, but how do you manage changes to the files, don't you have to redo the changes in each of the 3 projects?

**Comment by hhblaze** [comment]
Actually 2 projects, because UWP will work everywhere and will become the only project in the future. Standard DBreeze sources is more about support of .NET35.

**Comment by HakanL** [comment]
ok, good, thx for the additional info.
